### ISSUE TITLE
Html tags are not interpreted in textline elements

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#10]
HTML formatting tags just appear as plain text instead of being interpreted. This will be hard to implement, due to limitations of EaselJS. On [their website](http://www.createjs.com/docs/easeljs/classes/Text.html) they state:

```
Please note that Text does not support HTML text, and can only display one font style at a time. To use multiple font styles, you will need to create multiple text instances, and position them manually.
```

They also provide a solution:

```
Note that as an alternative to Text, you can position HTML text above or below the canvas relative to items in the display list using the localToGlobal method, or using DOMElement.
```

but what I concur from further documentation is that you will lose functionalities that normal text elements do have (events, detect if being clicked, etc.). We need to discuss if this is important (or can be solved another way), and determine if doing this will cause problems in fullscreen mode.

**Comment by shyras** [comment]
Maybe a nice quikc solution on
https://github.com/miohtama/Krusovice/blob/master/src/tools/html2svg2canvas.js
, although it would make the system dependable on svg.

2016-07-22 14:05 GMT+02:00 Daniel Schreij notifications@github.com:

**Comment by dschreij** [comment]
As long as this doesn't have a large overhead (e.g. takes seconds) and is done in the prepare phase, I think this is a viable solution.

**Comment by dschreij** [comment]
More info for the svg to canvas method, for further reference:

http://badassjs.com/post/12473322192/hack-of-the-day-rendering-html-to-a-canvas
http://robert.ocallahan.org/2011/11/drawing-dom-content-to-canvas.html

Would you like to give this a go, Jaap? or shall I assign myself to this task?

**Comment by dschreij** [comment]
I will look into this one; I don't think it will be easy

**Comment by dschreij** [comment]
In a rough (but working!) version, I have implemented the rendering of text with HTML markup on the canvas, by using the method of embedding the HTML in a SVG. It still needs to be extensively tested, but the first results look very promising. I still want to clean up the code a bit, and see if I can pull apart the monster-code in canvas.text() into smaller functions.

**Comment by dschreij** [comment]
Code is cleaned up, and the HTML rendering works nicely.
