### ISSUE TITLE
Sketchpad TextLine elements not Unicode safe

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#105]
If you add a non-ASCII character, such as an emoji, to a `sketchpad`, a crash occurs. If you add text with a special character embedded in it, such as 'tést', the experiment does not crash, but the text is rendered only up to the point of the special character (so 't'). I assume that both problems have the same underlying cause.

This textline:

~~~
draw textline center=1 color=white font_bold=no font_family=serif font_italic=no font_size=32 html=yes show_if=always text="😀" x=0 y=0 z_index=0
~~~

Results in this error:

![image](https://user-images.githubusercontent.com/594936/46260205-2a3c1100-c4e3-11e8-9a9e-c013e89d92a0.png)

**Comment by dschreij** [comment]
I am not experiencing this error!
I've tested it on Ubuntu 18.04 with Chromium 69.0.3497.81 and Firefox 62.0. Could you provide some info about the context? Is this an error with Edge again?

What I do notice however, is that the emoji is rendered completely different in both browsers. In chrome it is shown as an outlined mono-color shape, while FireFox shows a full-color emoji image. This is possibly undesirable as Chrome and Firefox users get to see different things clashing with a uniform experience across all participants.

**Comment by smathot** [comment]
Never mind, I cannot reproduce the error either. Strange … I must have messed something up version-wise.

> What I do notice however, is that the emoji is rendered completely different in both browsers. In chrome it is shown as an outlined mono-color shape, while FireFox shows a full-color emoji image. This is possibly undesirable as Chrome and Firefox users get to see different things clashing with a uniform experience across all participants.

It's not ideal, but I think we should accept that for now.
