### ISSUE TITLE
OSWeb does not play well with Qualtrics

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#108]
Even though it works well separately, the osweb libs do not work within Qualtrics, spitting out cryptical error messages:

<img width="580" alt="screen shot 2018-10-04 at 09 27 53" src="https://user-images.githubusercontent.com/689044/46459015-f4837a80-c7b7-11e8-9025-2304c8eb2e3b.png">

**Comment by dschreij** [comment]
@smathot you made more progress with getting osweb to work within Qualtrics, right? you got to the point where Qualtrics complains about the embedded logo as base64, if I'm correct, which seems a bit ahead of this error. Did you use the standalone export of OpenSesame for this, or did you manually compose an experiment for Qualtrics?

**Comment by smathot** [comment]
I used a special export in the OSWEB extension, which I've since removed. However, I suggest that we don't invest any effort in Qualtrics for now. JATOS gives us what we need, and it's free too.

**Comment by dschreij** [comment]
Solved, by modifying the webpack.config.js.
