### ISSUE TITLE
arrow elements are not rendered correctly

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#11]
Arrows are not correctly drawn to the canvas

**Comment by shyras** [comment]
I overlooked that you assigned this bug hunt to yourself. I still have to get used to a multi development style ;)  This bug is solved, but gives also a new smaller bug. Drawing of arrows with thick lines is not the same as in OpenSesame.

**Comment by dschreij** [comment]
No worries, I hadn't started yet ;). Nice work though. Let's keep the task here for now until we've reviewed it and solve the bug.

**Comment by dschreij** [comment]
Arrows are drawn in a different way by each backend in OpenSesame, often resulting in some minor inconsistenties, so it's no surprise that the osweb backend shows some minor deviations too. Still, I think the result is pretty good:

<img width="664" alt="screenshot 2016-07-27 12 24 21" src="https://cloud.githubusercontent.com/assets/689044/17172415/4cc36cfc-53f5-11e6-8f82-cf8ff63f706b.png">

The only thing that's a bit 'off' to my eyes, is that the final stroke of the polygon is not long enough. If we can just elongate it a bit somehow, then we should get perfect arrows. The rest seems quit in order. 

What do you say @smathot? Of course this needs to be fixed, but the result is quite good and this shouldn't be considered as a 'deal breaker' problem, I think.

**Comment by smathot** [comment]
Yes that looks pretty good! Doesn't OpenSesame have the same issue? It must result from the width not being added to the length of the line, if you see what I mean. If the length of the last line is increased by half the penwidth I think it will be fine.

**Comment by dschreij** [comment]
I think it also indeed happens like this in OS itself. I will close this issue for now, because it will most likely work correctly if we fix this problem in the polygon function, which is assigned at #16
