### ISSUE TITLE
Repeat_cycle item gives TypeError

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#115]
When adding a `repeat_cycle` item to an experiment, the following error occurs. I tested this with the latest code snapshot (1.2.3).

![image](https://user-images.githubusercontent.com/594936/49870899-0ff0ae80-fe15-11e8-8340-4635323090f8.png)

**Comment by shyras** [comment]
Ik heb even gekeken, zit een stomme typfout in 'repeat_cycle.js' in regel 50. Er staat 'this.epxeriment' i.p.v. 'this.experiment'. Ik denk dat na aanpassing de fout opgelost is.
