### ISSUE TITLE
Stricter audo playback policies on Chrome

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#117]
As of Chrome 70, an audio context can only be started with a user gesture (e.g. mouse click) on the page. Osweb (or rather the pixi library that it uses) actively warns for this in the console:

```
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.
```

However, I experience no trouble whatsoever with audio when running the Capybara or Gaze cueing experiment, but I'm not convinced there is no problem. These experiments both involve mouse interactions, and I read reports that keypresses or not counted as user gestures, so experiments that only involve keypresses may still have no audio playback here. We should carefully test this, and keep our eyes open for reports about this of osweb users.

**Comment by shyras** [comment]
I think this is partially solved due to the click screen used at the
beginning of osweb. I believe activation of the full screen mode must also
be approved by a mouse click.



Op do 13 dec. 2018 om 16:52 schreef Daniel Schreij <notifications@github.com

**Comment by smathot** [comment]
Let's close this until we actually notice any issues with it.
