### ISSUE TITLE
Safari does not allow keyboard input in fullscreen mode

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#119]
I was reading through the docs of jsPsych (https://www.jspsych.org/overview/fullscreen/) and the following paragraph at the bottom of the page caught my attention:

> Safari does not support keyboard input when the browser is in fullscreen mode. Therefore, the function will not launch fullscreen mode on Safari. The experiment will ignore any trials using the fullscreen plugin in Safari.

This of course is also relevant for Osweb when running in fullscreen mode, so we should keep an eye out for this (and maybe disable fullscreen mode on Safari?)

**Comment by smathot** [comment]
I just tried it on my test Mac with Safari 12.0.1. Here keyboard input does work in fullscreen mode, but there's an odd side-effect: Every key press gives a beep, one of these standard Mac sounds. There are no beeps when the experiment isn't fullscreen. What happens on your Mac?

**Comment by dschreij** [comment]
The same for me. I think that page or at least section of the jspsych documentation is outdated. Things change fast in the browser world.
