### ISSUE TITLE
Create an overview of supported browsers

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#126]
I have run OSWeb experiments successfully on most commonly used browsers. However, we don't seem to have clear requirements. We don't need to have an exhaustive list of all supported browsers, but we do need a list that will work *at least*.

Here's a stub:

- __Google Chrome / Chromium__ [version number] and higher
- __Firefox__ [version number] and higher
- __Safari__ [version number] and higher
- __Microsoft Edge__ [version number] and higher
- __Internet Explorer__ not supported (?)

**Comment by dschreij** [comment]
This is helpful: https://kangax.github.io/compat-table/es6/
I currently use the `babel-env` preset, which transpiles to es6 as far as I know, so we could adhere to that table. Let me doublecheck to be sure though...

**Comment by dschreij** [comment]
I added [browserlist integration](https://github.com/browserslist/browserslist) in the [coroutines PR](https://github.com/shyras/osweb/pull/130), as I already made some changes to the build configs in there, and didn't want to cause git conflicts by also making them in another branch.

The list of supported browsers can be shown by calling `npx browserslist` which currently shows the following supported browser versions for me:

```
and_chr 70
and_uc 11.8
android 4.4.3-4.4.4
chrome 70
chrome 69
chrome 68
chrome 67
chrome 63
chrome 49
edge 17
firefox 63
firefox 62
firefox 52
ie 11
ios_saf 12
ios_saf 11.3-11.4
ios_saf 11.0-11.2
ios_saf 10.3
ios_saf 10.0-10.2
op_mini all
opera 56
safari 12
safari 11.1
samsung 4
```

The target browsers can be set in package.json, under the `browserslist` entry. Currently it is set to support browsers with > 0.25% market share, but of course we can make this threshold higher. Supporting only newer browsers makes the bundle sizes smaller, let's the code run faster (as these browsers are optimized for newer JS), and old browsers may have wonky timing anyway (I'm looking at you IE), so it might be undesirable to support them at all...

**Comment by dschreij** [comment]
Please let me know if the implemented solution is sufficient, so we may close this issue.

**Comment by smathot** [comment]
Yes, I think so. I made a more human-readable summary of this on the docs:

- https://osdoc.cogsci.nl/3.2/manual/osweb/#supported-browsers

**Comment by dschreij** [comment]
Great! Keep in mind thought that the 'fix' has been implemented in the coroutines branch, and thus only becomes available after that branch has been merged in one of the main branches.
