### ISSUE TITLE
Variably defined font_size gives DOMException

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#127]
In a `sketchpad`, when the `font_size` is variable, such as in the line below, a `DOMException` is thrown. I'm not sure whether this issue is specific to `font_size` or also affects other keywords.

~~~
draw textline center=1 color=white font_bold=no font_family=serif font_italic=12 font_size=[fsize] html=yes show_if=always text="OpenSesame 3.2 <i>Kafkaesque Koffka</i>" x=0 y=0 z_index=0
~~~

![image](https://user-images.githubusercontent.com/594936/53746056-abd40880-3ea0-11e9-8eb0-2675b09c5878.png)

**Comment by dschreij** [comment]
I fixed this for the TextLine element, but I think this problem will occur for all the other elements, in which variables in properties are also not parsed at all... This should be very easy to fix though; basically copy-pasting the code block that now does the variable evaluation in the the TextLine element to all the other elements should do the trick, but we need to test this...

**Comment by dschreij** [comment]
This should be properly fixed by https://github.com/shyras/osweb/pull/131

**Comment by dschreij** [comment]
Can you confirm that this is fixed?

**Comment by smathot** [comment]
Yes, it's fixed!
