### ISSUE TITLE
Noise and gabor functions implemented

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#13]
OpenSesame's canvas has options to draw Gabor and Noise patches. We might have to pre-render these, as I don't think it is viable to create these real-time using EaselJs. If we possibly make a new Canvas backend based on WebGL/three.js in the future, we could look into this again.

**Comment by shyras** [comment]
Methods for Gabor and Noise patched are implemented. Both methods must be reviewed.

**Comment by dschreij** [comment]
Cool! you can drag this task from Backlog to ready then so it will be picked up sooner. Great job!

**Comment by dschreij** [comment]
The methods work, but the appearance of the patches doesn't seem correct. In my test, the patches are shifted half a phase, resulting in the following screenshot:

<img width="735" alt="screenshot 2016-07-27 12 12 03" src="https://cloud.githubusercontent.com/assets/689044/17172062/b5eae70c-53f3-11e6-98b9-72eba956a625.png">

**Comment by dschreij** [comment]
Issue is outdates, as osweb user Pixi instead of easel now instead. Noise and Gabor patches still don't work correcly, but this handled in issue:https://github.com/shyras/osweb/issues/85
