### ISSUE TITLE
logger: lack of introspection leads to ignoring of variables that are defined later

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#133]
Right now, when the `logger` is run for the time, OSWeb decides which variables to log. However, there is no introspection, and variables that are defined later on in the experiment are therefore ignored. This is undesirable, and also deviates from how OpenSesame normally works.

Ideally, we would implement proper introspection so that variables can also be detected before they are defined, following the same logic as OpenSesame

**Comment by dschreij** [comment]
This seems like pure magic to me. How can we detect variables before they are defined? Can you provide me with any leads on how you have done this in OS itself?

**Comment by smathot** [comment]
In OpenSesame, all well-behaved items implement a `var_info()` method that returns a list of `(var_name, description)` tuples. This is what the variable inspector relies on to see which variables exist when the experiment is not running. And it's what the `logger` relies on to see which variables might exist in the future.

However, maybe this isn't necessary in OSWeb, because the log format is different, and it's ok to add new variables to the log as the experiment progresses. So an alternative fix would be to change the behavior of `Log._get_all_vars()` such that it doesn't remember which variables exist (and thus doesn't take newly created variables into account). What do you think?

**Comment by dschreij** [comment]
> However, maybe this isn't necessary in OSWeb, because the log format is different, and it's ok to add new variables to the log as the experiment progresses. So an alternative fix would be to change the behavior of Log._get_all_vars() such that it doesn't remember which variables exist (and thus doesn't take newly created variables into account). What do you think?

I am still not following this completely. What are we trying to fix here? I understand that you need to know all variables beforehand in OpenSesame to be able to create a consistent csv file with the correct header row, but in osweb the variables are indeed logged in json format, for which this is less relevant, as new variables are added as {key: value} pairs in the variables array. What exactly do we need `Log._get_all_vars()` for in this context?

**Comment by dschreij** [comment]
Nevermind, I see what you mean now!

> So an alternative fix would be to change the behavior of Log._get_all_vars() such that it doesn't remember which variables exist (and thus doesn't take newly created variables into account).

I think you meant to say "and thus does take newly created variables into account"?

**Comment by smathot** [comment]
I did!

**Comment by dschreij** [comment]
This should be addressed by https://github.com/shyras/osweb/pull/144.
I am still completely puzzled by how you are able to determine/parse all variables that are set in `inline_script` items in OpenSesame, since this can't be done with a var_info() function. I'm telling you, black magic!

**Comment by smathot** [comment]
> I'm telling you, black magic!

Close: regular expressions.
