### ISSUE TITLE
advanced_delay: broken

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#135]
The `advanced_delay` item is broken. When a Uniform jitted is specified, there is no delay at all. When a Std. Dev jitter is specified, the delay is (seemingly) infinite. An example script to illustrate the issue was posted in this discussion:

- http://forum.cogsci.nl/discussion/5033/cant-get-advanced-delay-to-work#latest

**Comment by dschreij** [comment]
Fixed with https://github.com/shyras/osweb/commit/776d22e9733707564444d7582ba2fcc466b8eabc
