### ISSUE TITLE
file pool: files with non-ASCII characters are broken

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#137]
When using an image file with non-ASCII characters in the file name, a `TypeError` is thrown. I suspect that this is due to how the file pool is handled, and is not specific to use of images in a `sketchpad` (but I may be wrong, because I don't fully understand how the file pool is dealt with).

![image](https://user-images.githubusercontent.com/594936/55783339-737ea600-5aae-11e9-9343-d91725c5bc0e.png)

File names in the file pool all have pure ASCII names, to avoid ambiguity as to which encoding is used. And non-ASCII characters are represented with a `U+XXXX` notation. So `tèst.jpg` is stored as `tU+00E9.jpg` in the file pool. When extracting the file pool, this should be dealt with adequately.

**Comment by dschreij** [comment]
So, if I understand correctly, special characters in file names are explicitly converted to the U+XXXX format. If there is a lookup by osweb for instance for `tèst.jpg`, it should convert the è to U+00E9 and try to retrieve a file named `tU+00E9st.jpg` from the file pool?

**Comment by smathot** [comment]
OpenSesame implements this by renaming the files when they are extracted. So they are converted to the `U+XXXX` format only when saved to an experiment, and converted back to unicode filenames when extracted from an experiment. Like so:

- https://github.com/smathot/OpenSesame/blob/koffka/libopensesame/osexpfile/_osexpreader.py#L145

To the extent that this is applicable also in OSWeb, I feel that this is the easiest way to transparently handle this re-coding issue. What you're suggesting is handling the re-coding only when the files are looked up in the pool. That's also possible. I have no real preference, and I leave it up to you.

**Comment by dschreij** [comment]
Right, it's more clear to me now. The way osweb extracts an experiment is very untransparent at the moment, due to the library used to perform the extraction. I don't know how easy it is to rename files, so it might be a good idea to account for this encoding system later in the process. I will look into it.

**Comment by dschreij** [comment]
It's again (more) complicated than I hoped. It appears that the file names containing special characters are garbled at the moment that the files are extracted. This is the string representation of a loop item that I get of an extracted osexp file:
```
define loop pictures
	set source_file ""
	set source table
	set repeat 1
	set order random
	set description "Repeatedly runs another item"
	set cycles 3
	set continuous no
	set break_if_on_first yes
	set break_if never
	setcycle 0 fname "crÃªpe.jpg"
	setcycle 1 fname "soufflÃ©.jpg"
	setcycle 2 fname "niÃ§oise.jpg"
	run food
```
I use the `readAsString()` function of the extracted File object, which should parse the file contents as a UTF-8 string (https://github.com/InvokIT/js-untar#file-object). That is the way to go, right?

**Comment by dschreij** [comment]
Alright, part 1 of the problem is solved. All characters in the .osexp are decoded correctly now. The next step is to translate the U+XXXX characters back to their correct counterparts, and things should run smoothly. I will incorporate this operation into the `Transfer._processPoolItems()` function when I find the time.

**Comment by dschreij** [comment]
https://github.com/shyras/osweb/pull/148 addresses this issue.
