### ISSUE TITLE
Test Canvas copy() implementation

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#15]
Port the copy() function into the JS library

**Comment by dschreij** [comment]
I have implemented something, but I can think of no way that I can test this! I tried playing around in the console, but there was no easy way for me to create a canvas and add some shapes. This is really one of these moments unit tests would be handy...

Anyway, the copy function is very simple:

``` javascript
/**
  * Copies the contents of the passed canvas onto current one.   
  * @param  {osweb.canvas} canvas The source canvas to copy
  * @return {void}
  */
p.copy = function(canvas) {
        // Clear the contents of the current canvas
        this.clear()

        // Loop over the shapes on the passed canvas and copy them onto the current one
        canvas._container.children.forEach(function(shape){
            this._container.addChild(shape.clone(true));
        });
};
```

@shyras, do you think this will work, or how could I best test it?

**Comment by shyras** [comment]
Problem is that we can not test it by using inline code. Only solution is
to make a temporary hack in the code when executing a sketchpad object
(ugly!).

Regarding the above code, so far as i know there is also a clone method for
the container class.

**Comment by dschreij** [comment]
You are right! Wow, that I missed it while I have been attentively searching for it.
The function can be simplified to:

``` javascript
/**
 * Copies the contents of the passed canvas onto current one.
 * @param  {osweb.canvas} canvas The source canvas to copy
 * @return {void}
 */
p.copy = function(canvas) {
    this._container = canvas._container.clone(true);
};
```

It still needs to be tested though, but for now I'm placing this task back into _ready_

**Comment by dschreij** [comment]
I am indeed also no advocate  of such ugly hacks, For unit testing we should create some dummy experiment that runs through all possible functions of canvas and other classes and see if they show the expected behavior; sort of as you have already done for 'load from script' option, but much more extensive.

**Comment by dschreij** [comment]
@shyras. I know it's a while ago since you've worked on this, and you're occupied with other things at the moment, but do you remember if this is still an actual issue? It still mentions easel.js, while osweb has transition to pixi.js. Has the canvas.copy function been implemented there?

**Comment by shyras** [comment]
@dschreij Zover ik weet was deze opgelost, maar dat weet ik niet zeker meer. Code is aardig weggezakt. In mijn lokale verse staat bij de copy functie in het canvas object de volgende regel die gebruik maakt van pixi.js

copy(canvas) {
      this._container = canvas._container.clone(true);
  }
Ben nu veel bezig met vue.js voor onze onderzoeksportal. Blijf wel graag op de hoogte van je vorderingen

**Comment by dschreij** [comment]
Thanks! Ik ga het eens checken.
Vuejs is ook mijn favoriete view layer library en ik heb er heel veel mee gewerkt.
Ik zou ook eens kijken naar vuetify. Dat is een component library voor vuejs waarmee je heel snel interfaces kan maken.

**Comment by dschreij** [comment]
This one is hard to test, because the copy() function is not used by opensesame items internally afaik, and is mainly used in inline_script items (which we don't support yet).

I don't see a mention of the `clone()` method in the PIXI [docs for container](http://pixijs.download/dev/docs/PIXI.Container.html) by the way? I think they removed it from the class, so we have to fallback to my earlier proposed method: 
~~~javascript
copy (canvas) {
  this.clear()

  // Loop over the shapes on the passed canvas and copy them onto the current one
  for (const shape of canvas._container.children) {
    this._container.addChild(shape.clone())
  }
}
~~~

**Comment by dschreij** [comment]
Since the status of this issue is unclear, and it has not caused any problems sofar, I am closing it until it becomes relevant.
