### ISSUE TITLE
Canvas: polygon() implemented

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#16]

**Comment by dschreij** [comment]
There is currently not really a way to test this function, is there? You do not have the possibility to draw polygons in the sketchpad as far as I can see (or am I missing something @smathot  ?)

**Comment by shyras** [comment]
Nope, but the arrow methods in OpenSesame uses the polygon method
internally for drawing the arrow. To resemble this as much as possible I
thought to also implement this method.

2016-07-27 12:38 GMT+02:00 Daniel Schreij notifications@github.com:

**Comment by dschreij** [comment]
Ok, but arrow() is at the same time a good test of the function then and it seems to work well, except for maybe that the closing line is too short.

**Comment by shyras** [comment]
I will look into that point, strange bug.

2016-07-27 13:31 GMT+02:00 Daniel Schreij notifications@github.com:

**Comment by dschreij** [comment]
As Sebastiaan stated in #11, this is probably fixed by drawing the last line longer by 0.5*linewidth:

> Yes that looks pretty good! Doesn't OpenSesame have the same issue? It must result from the width not being added to the length of the line, if you see what I mean. If the length of the last line is increased by half the penwidth I think it will be fine.

These line endings are called a 'miter limits' and maybe they can simply be altered by a setting in EaselJS? A quick google search delivered: http://www.createjs.com/docs/easeljs/classes/Graphics.StrokeStyle.html where it states there is a variable miterLimit. (see also https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-miterlimit) 
Maybe by altering that setting, the problem can be fixed?

If this is fixed in the polygon() function, it  will likely also solve #11, as arrows are drawn using `polygon()`.

**Comment by dschreij** [comment]
Hmm thinking about this I again, I realised that the miterLimit will probably not solve this problem. Since the last line and first line are not connected, there will be no miter drawn between them... A solution could be to draw the first line again after the last line? This will cause a miter to be drawn between the (actual) last line, and the first line, I think.

And there is also this:
http://www.createjs.com/docs/easeljs/classes/Graphics.html#method_drawPolyStar
which states

> Draws a star if pointSize is greater than 0, or **a regular polygon** if pointSize is 0 with the specified number of points. 

so it might be that that function will close the polygon correctly. If it does draw polygons, its name drawPolyStar is inconveniently chosen though.

**Comment by shyras** [comment]
Using sebastiaans method to increase the line with half of the penwidht
does the trick.

2016-07-27 15:59 GMT+02:00 Daniel Schreij notifications@github.com:

**Comment by dschreij** [comment]
Nice work! Is it already on Github? I was just about to dive into the drawPolyStar function, but if your solution works then I'll leave that.

**Comment by shyras** [comment]
I forgot to push it, was a bussy day with all kinds of other stuff. Will do
it tomorrow at work right away.

2016-07-27 20:37 GMT+02:00 Daniel Schreij notifications@github.com:

**Comment by dschreij** [comment]
No rush! I was just curious how it looked. So take your time, even in the morning ;)  I actually also see now that the drawPolyStar() wouldn't not have worked at all (it was just able to draw hexagons, septagons, or octagons and such, but no real random polygons), so 'good on ya' that you manage to fix this.

**Comment by shyras** [comment]
the honour is al for Sebasitaan, i only changed the following line:
shape.graphics.lineTo(x + _0.5 \* penwidth_, y);

2016-07-27 20:45 GMT+02:00 Daniel Schreij notifications@github.com:

**Comment by dschreij** [comment]
Will this also work if the last line has another orientation than horizontal? you now extend the last line 0.5*penwidth in the horizontal direction, regardless of the direction in which the line itself is drawn. If the last line of the polygon is vertical for instance, I can imagine this has to become:

```
shape.graphics.lineTo(x, y + 0.5 * penwidth)
```

**Comment by smathot** [comment]
Right, this will need a bit of pythagoras. Say that the next-to-last point is `x1, y1`, and the last point is `x2, y2` then we need (untested):

```
a = atan2(y2-y1, x2-x1)
r = 0.5 * penwidth
x2 = x2 + cos(a) * r
y2 = y2 + sin(a) * r
```

In other words, we displace `x2, y2` in the direction that we came from by an amount of `0.5 * penwidth`.

**Comment by dschreij** [comment]
Even in OpenSesame itself, this is not perfect. The current html rendering is even better I dare to say. I think we can set this task to completed, and refine polygon drawing later (in a new task)
