### ISSUE TITLE
Implement classes/heartbeat.js

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#21]
Class is empty, but not used at the moment. (What is it intended for anyway @shyras?)

**Comment by shyras** [comment]
Is a copy of the heartbeat class defined in OpenSesame, does nothing yet.

**Comment by smathot** [comment]
The heartbeat implements the communication between the GUI process and the experiment process. So it's what makes the live variable inspector possible. I don't think it's applicable in osweb, so I suggest we remove the class and close this issue.

Or do you guys see a use for a heartbeat system in osweb?

**Comment by shyras** [comment]
Class has been removed in the current version so this issue can be closed.
