### ISSUE TITLE
Implement classes/response_store.js

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#25]
Class is defined, but empty and unused. What is it intended for?

**Comment by shyras** [comment]
Is a copy of the response_store class in OpenSesame 3.1.1, has no functionality yet.

**Comment by smathot** [comment]
I suggest we merge this into #24. `respone_info` and `response_store` are both part of the same system to keep track of response history.

**Comment by dschreij** [comment]
Alright, referencing this in #24
