### ISSUE TITLE
What to do with stored data in system/session.js

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#31]
Is used to store data in clients, to serve as fallbacks for possible system or connection failures

**Comment by dschreij** [comment]
But how are we going to get access to this data from the client after the connection has been restored. And what are the privacy implications of such a method?

**Comment by shyras** [comment]
Session data is automatically collected when the runner initializes. The
question if the information is usefull and if it is correct to collect this
info is open for discussion.

2016-07-22 16:17 GMT+02:00 Daniel Schreij notifications@github.com:

**Comment by dschreij** [comment]
@smathot is this OpenSesame specific? I don't think so, and I don't see the use for this module in osweb-client. Session maintenance is better left to the server. If you agree, I'll close this issue for now.

**Comment by dschreij** [comment]
This module does not longer seem relevant, especially when working with JATOS
