### ISSUE TITLE
Add more possibilities of reading in experiments

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#32]
In _system/runner.js_. In the test environment you can load local experiment files. The next step is to also be able to load from a database (partially working) and load experiments via a 'server call'. These options need to be specified more accurately

**Comment by shyras** [comment]
I will try to look into this the following days. 
- Read/write files directly to a server.
- Read/write files to a sql database

Maybe a good source to start with is https://github.com/jDataView/jBinary  This project has a nice example witch loads a tar file from a server, just what we need.

**Comment by dschreij** [comment]
Alright, let's place this in "in progress" then.

**Comment by shyras** [comment]
Reading an osexp file from server is working 
Writing a data file to server is working

**Comment by dschreij** [comment]
Cool, nice work! Do you regard this task as completed, or is there still a lot that needs to happen for it to be regarded as such?

**Comment by shyras** [comment]
Not completed yet, want to check/add some additional stuff for database access.

**Comment by dschreij** [comment]
The transfer module now auto-detects the source type and handles it accordingly. Since the description of this issue is kind of vague, and not really relevant for the client-side (this is more a job for the server-side), I'm closing it for now.
