### ISSUE TITLE
make js canvas compatible to python canvas with respect to style arguments

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#34]
We have to alter the JS canvas class so it follows the conventions of OpenSesame's canvas backend in Python. 

Over there, every canvas element is decorated by a function configurable, which inspects if (optional) keyword arguments are passed that define the style of the element to draw. The JS canvas currently cannot handle such keyword arguments and needs to explicitly passed parameters, such as color or line thickness. 

We thus need to think about how to solve this in JS, as this language doesn't support decorators (yet), and keyword arguments will also be a pain...

I think this issue has a priority, because it will influence the  shape of other canvas code that we write in the future.

**Comment by shyras** [comment]
So far as I know Javascript has no option for dynamic parameter
positioning, although it is possible to work with fixed optional
parameters. So we can do someting for all methods as done by fixdot where
we check if paramters are defined.

 p.fixdot = function(x, y, color, style) {

```
    // Check the color and style arguments.
    color = (typeof color === 'undefined') ? 'white' : color;
    style = (typeof style === 'undefined') ? 'default' : style;
```

}

2016-07-25 14:03 GMT+02:00 Daniel Schreij notifications@github.com:

**Comment by dschreij** [comment]
Yes, and we can pass the style object as a normal associative array (or dict type), we just need to think of a way to catch these optional arguments in the way they are passed to OpenSesame functions (as a **kwargs dict).

**Comment by shyras** [comment]
Mijn suggestie zou de onderstaande zijn met een dubbele check

function canvas.circle(x, y, r, style_args)
{
  this.color = ((typeof style_args === 'undefined') && (typeof
style_args.color !== 'undefined')) ? style_args.color : 'white';
  ...

2016-07-27 12:36 GMT+02:00 Daniel Schreij notifications@github.com:

**Comment by dschreij** [comment]
Yes, that is definitely an excellent solution. The problem we are facing actually occurs before we arrive at that point though. Python allows much more flexibility in the number of and way that arguments are passed. For instance, if you take this function circle, in python it is probably defined as:

``` python
def circle(x,y,r,**kwargs):
      """draw a circle"""
      color = kwargs.pop("color","white")
      linewidth = kwargs.pop("linewidth, 1)
      ...
```

This allows a user to pass an arbitrary number of keyword arguments in an arbitrary order, so these calls are equivalent:

``` python
circle(100, 100, 10, color="red", linewidth=5)
# same call, different order
circle(100, 100, 10, linewidth=5, color="red")
```

Javascript is less flexible than this because:
1. It doesn't allow default values for arguments, although the solution in your previous answer should solve this.
2. The order of arguments is important.

We thus have to find a way in which we capture all the keyword arguments that are related to style definitions, regardless of their order or presence, and put these in the `style_args` object, after which we can apply your solution above.

**Comment by dschreij** [comment]
Related to this problem, is that all drawing functions in the Python canvas implementation if OS work with so-called decorator functions, which JavaScript doesn't support (yet; there is a specification drafted for it in the next version). This decorator function actually takes care of the processing of the style args.

In OpenSesame the circle function is defined as:

``` python
@configurable
def circle(self, x, y, r, **style_args):
    ...
```

The circle function is decorated by the `configurable` function (designated by `@configurable` above the def, which means that whenever the circle function is called, it is actually passed as an argument to the `configurable` function, which can do stuff before and after the circle function is executed.
the configurable function is defined as:

``` python
def configurable(fnc):
    # ... ommitted for brevity
    def inner(self, *arglist, **kwdict):
        # Check for style arguments
        cfg = {}
        for key, val in list(kwdict.items()):
            if key in self.configurables:
                cfg[key] = val
                del kwdict[key]
        # If style arguments were specified, save the current
        # state of the canvas, and set the current style of the canvas
        # according to the style arguments.
        if len(cfg) > 0:
            old_cfg = self.get_config()
            self.set_config(**cfg)
        # Call the actual drawing function (can be any of line(), circle, etc.)
        retval = fnc(self, *arglist, **kwdict)
        # Restore the previous state of the canvas (e.g. reset the styles as
        # they were saved before the canvas drawing function was called)
        if len(cfg) > 0:
            self.set_config(**old_cfg)
        return retval
    # ... ommited for brevity
    return inner
```

Basically, the configurable decorator:
1. saves the currently set  style parameters of the canvas
2. sets the style of the canvas as specified by the passed style arguments
3. performs the drawing operation with these styles
4. resets the canvas style to what it was before (i.e. reapply the styles saved before executing the drawing function).

As I see it, there is currently no way of simply implementing this method of decorating functions in Javascript. The only possible thing that we could do is call the functions that save the old, set the new, and then restores the old canvas settings inside _each_ drawing function, maybe something like:

``` javascript
function canvas.circle(x, y, r, style_args) {
    // Implement in each drawing function:
    var old_styles = this.set_style(style_args);

    // < do the drawing operations >

    // Reset the styles
    this.set_style(old_styles)

function set_style(style_args){
    // Object containing old style
    var old_styles = {}
    // Save currently set color to old_styles object
    old_styles['color'] = this.color;
    // Process passed style_args object
    this.color = ((typeof style_args === 'undefined') && (typeof style_args.color !== 'undefined')) ? style_args.color : 'white'; 
    // ...
    return old_styles;
```

What do you think of such a structure @shyras ? Do you know if there would be a simple way to mimic the decorator structure of Python? also to @smathot, with the lack of decorators, would you approve such an implementation or do you have any insights that would improve it?

**Comment by shyras** [comment]
Obove suggestion is so far as I can see the best for now.

2016-07-27 15:34 GMT+02:00 Daniel Schreij notifications@github.com:

**Comment by dschreij** [comment]
Right? I'll see if I work on it soon.

**Comment by dschreij** [comment]
I investigated this issue further, and found there is a way to decorate functions in javascript! I now propose the following (which I am already at 50% with implementing to be honest).

Instead of storing the canvas styles directly in the canvas object, we can put them in a Styles object. I have defined the Styles object in the `classes` folder (and I'm not sure it belongs there, so tell me if it's wrong). I just created this object to be able to recognize it with `instanceof`, but it is empty otherwise:

``` javascript
(function() {
    // Definition of the class Style.
    function Styles() {};

    // Extend the class from its base class.
    var p = Styles.prototype;

    // Bind the Style class to the osweb namespace.
    osweb.Styles = Styles;
}());
```

In the canvas class, I store variables (and their default values) that define the drawing style of a stimulus in an instance of the Style object in the constructor :

``` javascript
 // Initialize a new styles object to store the default styles in.
this.styles = new osweb.Styles();
# Uses to be this.color = ...
this.styles.color = this.experiment.vars.foregound; // Foreground color of canvas.
// Etc.
```

Then, I have created a decorator function `_configurable`, which does the same as the opensesame decorator function: 
1. save the old style, 
2. set the new one,
3. draw the simulus
4. reset the old style

``` javascript
// Decorator function for applying styles
p._configurable = function(target_func){
    return function(){
        console.log('applying styles');

        // Check if a style object was passed by iterating through the 
        // arguments and check if one is an instance of Styles
        for(var i=0, var arg; i < arguments.length; i++){
            arg = arguments[i];
            if(arg instanceof Style){
                // store the style object
                var styles_pos = i;
                break;
            }
        };

        // If a styles object was found, activate it.
        if(styles_pos !== undefined){
            // Save original styles
            var orig_styles = this.styles;
            // Apply the style and remove the style object from the 
            // arguments list.
            this.styles = Array.prototype.splice.apply(arguments, 
                [style_pos, 1]);

            // Make sure all required style definitions are present in the 
            // current styles object, and copy those who aren't from the 
            // orig_styles object.
            for (var attrname in orig_styles){ 
                if(!this.styles.hasOwnProperty(attrname)){
                    this.styles[attrname] = orig_styles[attrname];
                } 
            }
        }
        // Call the original target function
        res = target_func.apply(this, arguments);

        // Reset original styles if they were changed.
        if(orig_styles !== undefined){
           this.styles = orig_styles;
        }
        // Return the result of the original drawing function
        return res;
    }
}
```

Each canvas drawing function that is dependent of style settings (which is almost all of them except images and such), has to be defined as a function that is passed to _configurable, for instance:

``` javascript
 p.arrow = p._configurable(function(sx, sy, ex, ey, body_width, body_length, head_width, fill, color, penwidth) {
      // ...
    });
```

It is also important that inside each drawing function, the references to style parameters are changed to these parameters in the styles object. For example, taking the circle() function:

``` javascript
p.circle = p._configurable(function(x, y, r, fill, color, penwidth) {
    var shape = new createjs.Shape();
    shape.graphics.setStrokeStyle(this.styles.penwidth);
    shape.graphics.beginStroke(this.styles.color);
    if (this.styles.fill == 1) {
        shape.graphics.beginFill(this.styles.color);
    }
    shape.graphics.drawCircle(x, y, r);

    // Add the line item to container.
    this._container.addChild(shape);
});
```

With this structure, we could mimic the OpenSesame way of defining styles for canvas elements. The only caveat is that we have to manually create the styles object whenever we define new styles. There is no way as far as I can see, to automatically translate optional arguments (keyword arguments do not exist in JS) into a styles object.

A final thing that we maybe should consider is to implement parameter checking in the Styles object. We should check if a set variable is among allowed values (for instance, `styles.penwidth = 5` will be accepted, but `styles.linewidth = 5` will throw an error)

What do you think @shyras and  @smathot ? Close enough to OS in python? ;)

**Comment by shyras** [comment]
Nice work, the only other solution for dynamic parameters I could think of
is to make use of the arguments object which is an array based object that
contains the arguments of a function.

2016-07-28 18:36 GMT+02:00 Daniel Schreij notifications@github.com:

**Comment by shyras** [comment]
Sorry, I saw that you already used the arguments object :) I would say,
continue with this implementation, good work!

2016-07-28 19:10 GMT+02:00 Bos, J. j.bos@rug.nl:

**Comment by smathot** [comment]
This looks excellent, and (if I understand it correctly) it is literally a decorator. The `@decoratorname` syntax of Python is just a shorthand for what you're doing here.

**Comment by dschreij** [comment]
Alright, I'll continue implementing this. Thanks for reviewing. This is indeed basic function decoration, but written more explicitly than is necessary in Python. The biggest challenge here is working around the lack of named arguments in JS, but we'll have to cope with that by the extra step of creating a Styles object where necessary then. And of course, testing is needed. After the canvas object is fully implemented I will start looking into UT.
