### ISSUE TITLE
Fonts not correctly interpreted

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#37]
Default OS font (Sans mono or Serif) is rendered as Times New Roman in browser. Make sure osweb uses something in the same style as the default OS fonts

**Comment by dschreij** [comment]
I've generated the following lookup object, with information from http://osdoc.cogsci.nl/3.1/manual/stimuli/text/:

``` json
default_fonts = {
        "sans" : "Droid Sans",
        "serif" : "Droid Serif",
        "mono" : "Droid Sans Mono",
        "chinese-japanese-korean" : "WenQuanYi Micro Hei",
        "arabic" : "Droid Arabic Naskh",
        "hebrew" : "Droid Sans Hebrew",
        "hindi" : "Lohit Hindi"
}
```

I have added Droid Sans, Serif and Mono to the Google fonts resource string; all other fonts however are not as easily obtainable. @smathot, what would you like to do with those? Add them manually? Or do you know an online repository to fetch them from? Or leave them for now?

**Comment by smathot** [comment]
I'd say we can leave them for now. The main reason for these fonts was to show non-Latin alphabets at all, but webbrowsers do that automatically anyway, regardless of the font that is used. So I think that `Droid Sans` can be used for all non-Latin fonts.
