### ISSUE TITLE
Various imperfections in sketchpad rendering

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#4]
It is my pleasure to christen the repository with a first issue!

I just tested all sketchpad drawing operations, using the test experiment that is part of OpenSesame's unittests:
- https://github.com/smathot/OpenSesame/blob/master/opensesame_unittest/data/sketchpad_test.osexp

Overall, things are rendered _remarkably well_, but here are a few things that don't work yet. What I noticed:
- Non-ascii text is not rendered correctly in `textline` elements
- Html tags are not interpreted in `textline` elements
- `arrow` elements are not rendered correctly
- Luminance-value colors (0-255) are not interpreted correctly
- `*-cross` fixdot styles are not implemented
- `noise` and `gabor` elements are not implemented

Ideally, as Daniel and I were discussing today, we would implement a similar unittest for osweb as there is for the regular OpenSesame. I'm not sure how to do this in JavaScript, but I'm sure it's possible..

Great work!

**Comment by shyras** [comment]
Let me then be the first one to solve this issue partially :)
- Non-ascii text rendering is working now
- cross fixdot style is working now

**Comment by dschreij** [comment]
Haha that's fast! I thought you were enjoying your weekend Jaap ;)
I'm going to add the remaining issues listed above as separate tasks, so we can indicate for them individually what their status is. I think it's best to keep all tasks/issues as elementary as possible, wouldn't you say?

**Comment by shyras** [comment]
It's raining outside :(

(Typical dutch weather)

2016-07-22 13:32 GMT+02:00 Daniel Schreij notifications@github.com:
