### ISSUE TITLE
Unittest: Syntax

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#43]
Ref:
- [opensesame_unittest.syntax](https://github.com/smathot/OpenSesame/blob/release/3.1.2/opensesame_unittest/syntax.py)

We need unittests to check if OpenSesame script is parsed correctly.
## Unsupported syntax

For now, I suggest we don't support:
- Inline Python scripting in text (`[=...]`) and condition (`=...`) statements
- `U+XXXX` syntax for Unicode (this was a hack before OpenSesame properly supported unicode)
## Item definition

And item is defined by a single `define` line, followed by zero or more lines of tab-indented definition lines, and ends and the first line that is no longer tab-indented.

```
define [item type] [item name]
    [cmd] [arglist] [keywords]
```
## Parsing of command, arguments, keywords

Ref:
- [libopensesame.syntax.syntax.parse_cmd](https://github.com/smathot/OpenSesame/blob/release/3.1.2/libopensesame/syntax.py#L176)

Commands have the following structure, where `cmd` is the name of a command, `arglist` is an unnamed, ordered list of arguments, and keywords is a named, unordered list of arguments.

```
[cmd] [arglist] [keywords]
```

Examples:

```
widget 0 0 1 1 label text="Some text"
set width 1024
```
## Multiline variables

Ref:
- [libopensesame.item.item.from_string](https://github.com/smathot/OpenSesame/blob/release/3.1.2/libopensesame/item.py#L270)

Multiline variables are start with `__[varname]__` and end with `__end__`.

```
__my_var__
One line
Another line
__end__
```
## Quoting and splitting

Refs:
- [libopensesame.syntax.syntax.quotable_symbol](https://github.com/smathot/OpenSesame/blob/release/3.1.2/libopensesame/syntax.py#L295)
- [libopensesame.syntax.syntax.compile_cond](https://github.com/smathot/OpenSesame/blob/release/3.1.2/libopensesame/syntax.py#L317)
- https://docs.python.org/2/library/shlex.html#parsing-rules

Strings should be splitted, and quotes handled, as specified in POSIX mode for the Python `shlex` module.

So these two are equivalent:

```
set width 1024
set width "1024"
```

But these aren't:

```
set title "Some title"
set title Some title
```

Literal quotes need to be escaped:

```
set title "Some \"title\""
```

And so do literal backslashes (by another backslash):

```
set path "c:\\"
```
## Variable names

Refs:
- [libopensesame.syntax.syntax.eval_text](https://github.com/smathot/OpenSesame/blob/release/3.1.2/libopensesame/syntax.py#L243)

If something between square brackets is a valid variable name, it is interpreted as a variable, otherwise it is left as is.

```
[this_is_a_variable]
[but this is just text between square brackets]
```

Variable names can be escaped:

`\[this]` is not a variable, but the text '[this]'
## Text evaluation
- [libopensesame.syntax.syntax.eval_text](https://github.com/smathot/OpenSesame/blob/release/3.1.2/libopensesame/syntax.py#L243)

Variables should be replaced in text strings following the logic described under Variable names.
## Conditional statements

Refs:
- [libopensesame.syntax.syntax.compile_cond](https://github.com/smathot/OpenSesame/blob/release/3.1.2/libopensesame/syntax.py#L317)
- [libopensesame.syntax.syntax.quotable_](https://github.com/smathot/OpenSesame/blob/release/3.1.2/libopensesame/syntax.py#L295)

Conditional statements are processed as follows:
- Variable names are replaced by `var.varname`
- All symbols are double-quoted unless they are `not`, `or`, `and`, `always`, `never`, or can be converted to `int`
- `always` is replaced by `True` and `never` is replaced by `False`. This is case-insensitive.
- Isolated `=` is replaced by `==`.

If the output is a valid Python statement, then the input was a valid OpenSesame conditional statement.

**Comment by smathot** [comment]
Ref:

- [opensesame_unittest.syntax](https://github.com/smathot/OpenSesame/blob/release/3.1.2/opensesame_unittest/syntax.py)

We need unittests to check if OpenSesame script is parsed correctly.


## Unsupported syntax

For now, I suggest we don't support:

- Inline Python scripting in text (`[=...]`) and condition (`=...`) statements
- `U+XXXX` syntax for Unicode (this was a hack before OpenSesame properly supported unicode)


## Item definition

And item is defined by a single `define` line, followed by zero or more lines of tab-indented definition lines, and ends and the first line that is no longer tab-indented.

	define [item type] [item name]
		[cmd] [arglist] [keywords]


## Parsing of command, arguments, keywords

Ref:

- [libopensesame.syntax.syntax.parse_cmd](https://github.com/smathot/OpenSesame/blob/release/3.1.2/libopensesame/syntax.py#L176)

Commands have the following structure, where `cmd` is the name of a command, `arglist` is an unnamed, ordered list of arguments, and keywords is a named, unordered list of arguments.

	[cmd] [arglist] [keywords]
	
Examples:
	
	widget 0 0 1 1 label text="Some text"
	set width 1024
	
	
## Multiline variables

Ref:

- [libopensesame.item.item.from_string](https://github.com/smathot/OpenSesame/blob/release/3.1.2/libopensesame/item.py#L270)

Multiline variables are start with `__[varname]__` and end with `__end__`.

	__my_var__
	One line
	Another line
	__end__
	
	
## Quoting and splitting

Refs:

- [libopensesame.syntax.syntax.quotable_symbol](https://github.com/smathot/OpenSesame/blob/release/3.1.2/libopensesame/syntax.py#L295)
- [libopensesame.syntax.syntax.compile_cond](https://github.com/smathot/OpenSesame/blob/release/3.1.2/libopensesame/syntax.py#L317)
- https://docs.python.org/2/library/shlex.html#parsing-rules
	
Strings should be splitted, and quotes handled, as specified in POSIX mode for the Python `shlex` module.

So these two are equivalent:

	set width 1024
	set width "1024"
	
But these aren't:

	set title "Some title"
	set title Some title
	
Literal quotes need to be escaped:

	set title "Some \"title\""
	
And so do literal backslashes (by another backslash):

	set path "c:\\"
	

## Variable names

Refs:

- [libopensesame.syntax.syntax.eval_text](https://github.com/smathot/OpenSesame/blob/release/3.1.2/libopensesame/syntax.py#L243)

If something between square brackets is a valid variable name, it is interpreted as a variable, otherwise it is left as is.

	[this_is_a_variable]
	[but this is just text between square brackets]
	
Variable names can be escaped:

`\[this]` is not a variable, but the text '[this]'


## Text evaluation

- [libopensesame.syntax.syntax.eval_text](https://github.com/smathot/OpenSesame/blob/release/3.1.2/libopensesame/syntax.py#L243)


Variables should be replaced in text strings following the logic described under Variable names.


## Conditional statements

Refs:

- [libopensesame.syntax.syntax.compile_cond](https://github.com/smathot/OpenSesame/blob/release/3.1.2/libopensesame/syntax.py#L317)
- [libopensesame.syntax.syntax.quotable_](https://github.com/smathot/OpenSesame/blob/release/3.1.2/libopensesame/syntax.py#L295)

Conditional statements are processed as follows:

- Variable names are replaced by `var.varname`
- All symbols are double-quoted unless they are `not`, `or`, `and`, `always`, `never`, or can be converted to `int`
- `always` is replaced by `True` and `never` is replaced by `False`. This is case-insensitive.
- Isolated `=` is replaced by `==`.

If the output is a valid Python statement, then the input was a valid OpenSesame conditional statement.

**Comment by dschreij** [comment]
All checks pass, except for the throwing of an exception at an illegal command (ommitted quote for instance)

**Comment by dschreij** [comment]
All the unit test pass for syntax, and I see that @smathot also added a lot of edge conditions (am I right?).
Is this still really an open issue? Do we have specific cases in which the syntax parsing of osweb fails?

**Comment by dschreij** [comment]
@smathot. Are the syntax unit tests currently sufficient? If yes, let's close this issue.

**Comment by smathot** [comment]
I think so!
