### ISSUE TITLE
Give useful error messages

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#44]
Right now, if an experiment fails to load, the browser just hangs, and the user has to look in the console to see what went wrong. For example, when trying to run an experiment with PyGaze plugins in it (to see how osweb handles that), the console prints:

```
osweb - 3.0.044 (01-08-2016)
debug.js:38 Unknown class definition within osweb script - pygaze_log
debug.js:39 osweb has stopped running due a fatal error.
debug.js:45 Uncaught Error: Unknown class definition within osweb script - pygaze_log
```

But other than that there is no indication that anything went wrong. Ideally the user would be informed of error messages in a more visible way.

**Comment by dschreij** [comment]
Right! I have been thinking about that one already too. 

We also use the notification systems that many modern browsers have built-in: https://developer.mozilla.org/en/docs/Web/API/notification. This is the easiest way to go I think.

However, there are some prettier options:

https://alertifyjs.org/#getting-started
http://wavded.github.io/humane-js/

**Comment by dschreij** [comment]
Per aba7d90 error messages and other important information is shown using alertify.js
