### ISSUE TITLE
Some keys are ignored as Allowed Responses in keyboard_response

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#46]
For example, 'space' is ignored when entered as an allowed response in a keyboard response. The  same may be true for other keys--I haven't tried exhaustively.

However, many other keys do work as expected. For example, the 'a' is interpreted correctly when entered as an allowed response.

**Comment by shyras** [comment]
Fixed. Small bug, default value for space was set to 'space' instead of ' '.
