### ISSUE TITLE
Uncaught DOMException when running local file or internal script

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#57]
When I try to run a local file or the internal script, I receive the following error:

![image](https://cloud.githubusercontent.com/assets/594936/22014459/21ee7198-dc9e-11e6-83f0-46eea40ff3b7.png)

To reproduce the error:

- Load the page (running on `localhost:8000`)
- Click Internal Script → Run
- Select Subject Nr 0
- Nothing happens (i.e. the canvas is black)
- When I click on the canvas, I get the error shown above

The same happens when I try to run a local file.

(Tried with latest commit 5501a93,)

**Comment by shyras** [comment]
I did some modifications to get the HTML rendering working again (canvas.js), and I used the following lines for that:

var url = DOMURL.createObjectURL(svg);
img.onload = function () {
ctx.drawImage(img, 0, 0);
DOMURL.revokeObjectURL(url);

I think that something triggers a security issue which did not happen on my local system. I will see into this.

**Comment by shyras** [comment]
This is a known bug when drawing SVG to canvas in Chrome. Used Daniels old method to get everything running again.
