### ISSUE TITLE
Text with HTML tags not visible at all

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#59]
After the fix of #57, text with html tags is not shown at all anymore. HTML was already improperly rendered, as described in #52, but now nothing is visible at all.

Below I attached a reference script. The `sketchpad` should look like:

![image](https://cloud.githubusercontent.com/assets/594936/22072222/ebe0f42c-dda1-11e6-8cef-d6b270794a9b.png)

But in osweb it looks like (i.e. only text without HTML tags is visible):

![image](https://cloud.githubusercontent.com/assets/594936/22072246/0221c662-dda2-11e6-8af5-c51d85d149eb.png)

~~~
---
API: 2
OpenSesame: 3.1.5a3
Platform: posix
---
set width 1024
set uniform_coordinates yes
set title "New experiment"
set subject_parity even
set subject_nr 0
set start experiment
set sound_sample_size -16
set sound_freq 48000
set sound_channels 2
set sound_buf_size 1024
set round_decimals 2
set height 768
set fullscreen no
set form_clicks no
set foreground white
set font_underline no
set font_size 18
set font_italic no
set font_family mono
set font_bold no
set experiment_path "/home/sebastiaan/Tmp/opensesame"
set disable_garbage_collection yes
set description "The main experiment item"
set coordinates uniform
set compensation 0
set canvas_backend xpyriment
set bidi no
set background black

define sequence experiment
	set flush_keyboard yes
	set description "Runs a number of items in sequence"
	run welcome always

define sketchpad welcome
	set start_response_interval no
	set reset_variables no
	set duration keypress
	set description "Displays stimuli"
	draw textline center=0 color=white font_bold=no font_family=serif font_italic=no font_size=32 html=yes show_if=always text="some text <i>with</i> html" x=-160.0 y=-32.0 z_index=0
	draw textline center=1 color=white font_bold=no font_family=serif font_italic=no font_size=32 html=yes show_if=always text="some text without html" x=0.0 y=-96.0 z_index=0
	draw textline center=1 color=white font_bold=no font_family=serif font_italic=no font_size=32 html=yes show_if=always text="some<br />multiline<br />text" x=0.0 y=128.0 z_index=0
~~~

**Comment by dschreij** [comment]
In line with this issue, I've been searching a bit, and I think we can use [normalize.css](https://necolas.github.io/normalize.css/)  or [reboot.css](http://v4-alpha.getbootstrap.com/content/reboot/)  to reset the styles in the div we use to prerender the contents. Alternatively we can give both the prerender div and the div rendered in the svg a class that ensures they adhere to the same styles, so the required dimensions of the svg are calculated correctly.

**Comment by shyras** [comment]
I think this is caused by the selected font family, I have seen this problem before. I think that if yuo replace the font name from Serif into Arial or Times it might work, although that is not a proper solution. I will look into this, but that can take som time.  SGV and fonts are not my specialty.

**Comment by smathot** [comment]
> I think this is caused by the selected font family, I have seen this problem before. I think that if yuo replace the font name from Serif into Arial or Times it might work, although that is not a proper solution.

It doesn't, actually. I've tried a few different fonts, also variations (i.e. "Times" or "Times New Roman", etc.), but nothing is shown. The same fonts do work in the non-HTML string.

**Comment by shyras** [comment]
I do aggree, something very stanges happens, so I will look further in this. At this moment we can state that only the non-html works properly

**Comment by shyras** [comment]
Current version renders both html and non html text
