### ISSUE TITLE
Form_base not working correctly

### ISSUE THREAD

**Issue by cruchichu** [shyras/osweb#75]
I have a form base with the following script:

set timeout infinite
set spacing 10
set rows "1;6;1;1"
set only_render no
set margins "50;50;50;50"
set cols 1
set _theme gray
widget 2 0 1 1 label text="Please type the name in the box and press ENTER."
widget 0 0 1 1 label text="This is a[obj_name]."
widget 3 0 1 1 text_input focus=yes return_accepts=yes var=type_in
widget 1 0 1 1 image path="[obj_png]"

The only thing displying is the first row: "this is a[obj_name]" (with the appropriate name retrieved from the variable obj_name). 

The experiement gets stuck there because it's not showing the buttons (or the image for that matter). 

It also is not showing the HTML formatting (e.g. font size and br, it shows <span size=50> and <br />), but I think that has been said before

Thanks!

**Comment by smathot** [comment]
Thanks for your feedback! We've decided to *not* implement forms in OSWeb for now, so I'm closing this issue.
