### ISSUE TITLE
Implement unit tests

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#8]
We need to implement a system of unit testing before we continue with working on new features.

I have done some background research and the most widely adopted and easiest to use system appears to be [Jest](https://facebook.github.io/jest/), so I have already translated the tests to that system (changes were minimal).

**Comment by dschreij** [comment]
@smathot This isn't really an issue, but an ongoing process. Shall we close it here to keep the issues 'pure' and add this is a note on the osweb project board instead?

**Comment by smathot** [comment]
Agreed!
