### ISSUE TITLE
canvas._getTextBaseline() does not appear to work

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#87]
The `canvas._getTextBaseline()` does not appear to work correctly.
The below statement
~~~javascript
console.log(canvas._getTextBaseline('Testing'))
~~~
simply returns
~~~javascript
{ ascent: 0, height: 0, descent: 0 }
~~~
This is returned with any set of parameters that is passed to `_getTextBaseline()`.

I'm not sure what this function is intended to do or in what case it is used. @shyras could you enlighten me a bit on this?

**Comment by shyras** [comment]
Hi Daniel,

So far as I can remember I had some diffeculties calculating the position
of the text elements using HTML. This function calculated the position of
the text element using some 'magic' HTML goeroe.

Regards,
Jaap

2018-06-29 22:06 GMT+02:00 Daniel Schreij <notifications@github.com>:

**Comment by dschreij** [comment]
Seems to work after all, only needs context to be active
